### ISSUE TITLE
单独使用七牛云报错了

### ISSUE THREAD

**Issue by kinsou** [Angel-fund/sslmanage#1]
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from sslmanage.qiniu_ssl import QnCertManager
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/sslmanage-1.0.4-py3.5.egg/sslmanage/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/sslmanage-1.0.4-py3.5.egg/sslmanage/upyun_ssl.py", line 86
    response = req(f'https://console.upyun.com{urls}', **kwargs)

**Comment by Angel-fund** [comment]
看看项目中Python 文件名有没有和Python的包名冲突
